name: Deploy tag

on:
  workflow_dispatch:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy jar to the server
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate the package
        run: mvn -B package --file pom.xml
      - name: Remove existing jars on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: rm -rf /home/pi/Documents/PostAutoIsAJoke/production/*.jar
      - name: Deploy with ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/
          remote: Documents/PostAutoIsAJoke/production/
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
